-- GATE persistence foundation: additive, idempotent; records remains retained.
-- Production tables were created manually before this migration. Do not alter or drop them.
CREATE TABLE IF NOT EXISTS gate_v2_buses (id TEXT PRIMARY KEY, week_group TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, bus_type TEXT GENERATED ALWAYS AS (json_extract(data,'$.bus_type')) VIRTUAL, status TEXT GENERATED ALWAYS AS (json_extract(data,'$.status')) VIRTUAL, departed_at TEXT GENERATED ALWAYS AS (json_extract(data,'$.departed_at')) VIRTUAL, arrived_at TEXT GENERATED ALWAYS AS (json_extract(data,'$.arrived_at')) VIRTUAL);
CREATE TABLE IF NOT EXISTS gate_v2_dorms (id TEXT PRIMARY KEY, type TEXT NOT NULL CHECK(type='dorm'), week_group TEXT, data TEXT NOT NULL CHECK(json_valid(data)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, dorm_name TEXT GENERATED ALWAYS AS (json_extract(data,'$.dorm_name')) VIRTUAL, dorm_state TEXT GENERATED ALWAYS AS (json_extract(data,'$.state')) VIRTUAL, phase TEXT GENERATED ALWAYS AS (json_extract(data,'$.phase')) VIRTUAL, current_load INTEGER GENERATED ALWAYS AS (json_extract(data,'$.current_load')) VIRTUAL, max_load INTEGER GENERATED ALWAYS AS (json_extract(data,'$.max_load')) VIRTUAL);
CREATE TABLE IF NOT EXISTS gate_v2_archives (id TEXT PRIMARY KEY, type TEXT NOT NULL CHECK(type='archive'), week_group TEXT, data TEXT NOT NULL CHECK(json_valid(data)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT GENERATED ALWAYS AS (json_extract(data,'$.archived_at')) VIRTUAL);
CREATE TABLE IF NOT EXISTS gate_v2_config (id TEXT PRIMARY KEY, type TEXT NOT NULL CHECK(type='config'), week_group TEXT, data TEXT NOT NULL CHECK(json_valid(data)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, config_key TEXT GENERATED ALWAYS AS (json_extract(data,'$.key')) VIRTUAL);
CREATE TABLE IF NOT EXISTS gate_v2_sound_events (id TEXT PRIMARY KEY, type TEXT NOT NULL CHECK(type='sound_event'), week_group TEXT, data TEXT NOT NULL CHECK(json_valid(data)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_gate_v2_bus_wg_status ON gate_v2_buses(week_group,status);
CREATE INDEX IF NOT EXISTS idx_gate_v2_bus_dispatch ON gate_v2_buses(week_group,departed_at);
CREATE INDEX IF NOT EXISTS idx_gate_v2_dorm_wg_state ON gate_v2_dorms(week_group,dorm_state);
CREATE INDEX IF NOT EXISTS idx_gate_v2_dorm_wg_name ON gate_v2_dorms(week_group,dorm_name);
CREATE INDEX IF NOT EXISTS idx_gate_v2_archives_wg_time ON gate_v2_archives(week_group,archived_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_v2_config_key ON gate_v2_config(config_key);
CREATE INDEX IF NOT EXISTS idx_gate_v2_sound_wg_created ON gate_v2_sound_events(week_group,created_at);

CREATE TABLE IF NOT EXISTS gate_input_drafts (draft_id TEXT NOT NULL PRIMARY KEY, proposed_week_group TEXT, rows_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(rows_json) AND json_type(rows_json)='array'), receiving_windows_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(receiving_windows_json) AND json_type(receiving_windows_json)='object'), import_review_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(import_review_json) AND json_type(import_review_json)='object'), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','consumed','abandoned')), revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), consumed_at TEXT, CHECK(proposed_week_group IS NULL OR length(trim(proposed_week_group))>0), CHECK(status<>'consumed' OR consumed_at IS NOT NULL));
CREATE TABLE IF NOT EXISTS gate_week_groups (cycle_id TEXT NOT NULL PRIMARY KEY, week_group TEXT NOT NULL CHECK(length(trim(week_group))>0), state TEXT NOT NULL CHECK(state IN ('initializing','active','closing','needs_recovery','closed')), source_draft_id TEXT REFERENCES gate_input_drafts(draft_id) ON DELETE RESTRICT, receiving_windows_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(receiving_windows_json) AND json_type(receiving_windows_json)='object'), archive_id TEXT, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), activated_at TEXT, closed_at TEXT, CHECK(state<>'closed' OR (archive_id IS NOT NULL AND closed_at IS NOT NULL)));
CREATE TABLE IF NOT EXISTS gate_workflow_operations (operation_id TEXT NOT NULL PRIMARY KEY, idempotency_key TEXT NOT NULL UNIQUE CHECK(length(trim(idempotency_key))>0), action TEXT NOT NULL CHECK(action IN ('initialize','closeout')), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','archive_verified','completed','failed','needs_recovery')), cycle_id TEXT REFERENCES gate_week_groups(cycle_id) ON DELETE RESTRICT, draft_id TEXT REFERENCES gate_input_drafts(draft_id) ON DELETE RESTRICT, request_fingerprint TEXT NOT NULL CHECK(length(trim(request_fingerprint))>0), archive_id TEXT, phase TEXT, error_code TEXT, attempt_count INTEGER NOT NULL DEFAULT 1 CHECK(attempt_count>=1), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), completed_at TEXT, CHECK(status<>'archive_verified' OR action='closeout'));
CREATE TABLE IF NOT EXISTS gate_audit_events (event_id TEXT NOT NULL PRIMARY KEY, cycle_id TEXT REFERENCES gate_week_groups(cycle_id) ON DELETE RESTRICT, operation_id TEXT REFERENCES gate_workflow_operations(operation_id) ON DELETE RESTRICT, entity_type TEXT NOT NULL CHECK(length(trim(entity_type))>0), entity_id TEXT NOT NULL CHECK(length(trim(entity_id))>0), event_type TEXT NOT NULL CHECK(length(trim(event_type))>0), actor_role TEXT NOT NULL CHECK(actor_role IN ('instructor','airman','squadron','system')), prior_version INTEGER NOT NULL DEFAULT 0 CHECK(prior_version>=0), resulting_version INTEGER NOT NULL DEFAULT 0 CHECK(resulting_version>=prior_version), metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) AND json_type(metadata_json)='object'), occurred_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
CREATE TABLE IF NOT EXISTS gate_archive_amendments (amendment_id TEXT NOT NULL PRIMARY KEY, archive_id TEXT NOT NULL CHECK(length(trim(archive_id))>0), cycle_id TEXT REFERENCES gate_week_groups(cycle_id) ON DELETE RESTRICT, amendment_number INTEGER NOT NULL CHECK(amendment_number>0), amendment_type TEXT NOT NULL CHECK(length(trim(amendment_type))>0), reason TEXT NOT NULL CHECK(length(trim(reason))>0), changes_json TEXT NOT NULL CHECK(json_valid(changes_json) AND json_type(changes_json)='object'), actor_role TEXT NOT NULL CHECK(actor_role IN ('instructor','system')), created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), UNIQUE(archive_id,amendment_number));
CREATE INDEX IF NOT EXISTS idx_gate_draft_status_updated ON gate_input_drafts(status,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_draft_proposed_wg ON gate_input_drafts(proposed_week_group,status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_gate_single_live_week_group ON gate_week_groups((1)) WHERE state<>'closed';
CREATE INDEX IF NOT EXISTS idx_gate_week_group_history ON gate_week_groups(week_group,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_workflow_status_updated ON gate_workflow_operations(status,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_workflow_cycle_action ON gate_workflow_operations(cycle_id,action,created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_gate_workflow_active_cycle_action ON gate_workflow_operations(cycle_id,action) WHERE cycle_id IS NOT NULL AND status IN ('pending','running','archive_verified','needs_recovery');
CREATE INDEX IF NOT EXISTS idx_gate_audit_cycle_time ON gate_audit_events(cycle_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_audit_entity_time ON gate_audit_events(entity_type,entity_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_amend_archive_time ON gate_archive_amendments(archive_id,created_at DESC);
CREATE TRIGGER IF NOT EXISTS trg_gate_audit_no_update BEFORE UPDATE ON gate_audit_events BEGIN SELECT RAISE(ABORT,'audit events are append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_gate_audit_no_delete BEFORE DELETE ON gate_audit_events BEGIN SELECT RAISE(ABORT,'audit events are append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_gate_amend_no_update BEFORE UPDATE ON gate_archive_amendments BEGIN SELECT RAISE(ABORT,'archive amendments are append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_gate_amend_no_delete BEFORE DELETE ON gate_archive_amendments BEGIN SELECT RAISE(ABORT,'archive amendments are append-only'); END;
CREATE TRIGGER IF NOT EXISTS prevent_audit_event_update BEFORE UPDATE ON records WHEN OLD.type='audit_event' BEGIN SELECT RAISE(ABORT,'audit events are append-only'); END;
CREATE TRIGGER IF NOT EXISTS prevent_audit_event_delete BEFORE DELETE ON records WHEN OLD.type='audit_event' BEGIN SELECT RAISE(ABORT,'audit events are append-only'); END;

-- Keep legacy reads and new typed tables synchronized in the same SQLite transaction.
-- Existing data must first pass the complete parity check documented in the cutover runbook.
CREATE TRIGGER IF NOT EXISTS gate_mirror_records_insert AFTER INSERT ON records BEGIN
 INSERT INTO gate_v2_buses(id,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='bus' ON CONFLICT(id) DO UPDATE SET week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_dorms(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='dorm' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_archives(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='archive' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_config(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='config' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_sound_events(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='sound_event' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
END;
CREATE TRIGGER IF NOT EXISTS gate_mirror_records_update AFTER UPDATE ON records BEGIN
 DELETE FROM gate_v2_buses WHERE id=OLD.id AND OLD.type='bus' AND NEW.type<>'bus';
 DELETE FROM gate_v2_dorms WHERE id=OLD.id AND OLD.type='dorm' AND NEW.type<>'dorm';
 DELETE FROM gate_v2_archives WHERE id=OLD.id AND OLD.type='archive' AND NEW.type<>'archive';
 DELETE FROM gate_v2_config WHERE id=OLD.id AND OLD.type='config' AND NEW.type<>'config';
 DELETE FROM gate_v2_sound_events WHERE id=OLD.id AND OLD.type='sound_event' AND NEW.type<>'sound_event';
 INSERT INTO gate_v2_buses(id,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='bus' ON CONFLICT(id) DO UPDATE SET week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_dorms(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='dorm' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_archives(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='archive' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_config(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='config' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
 INSERT INTO gate_v2_sound_events(id,type,week_group,data,created_at,updated_at) SELECT NEW.id,NEW.type,NEW.week_group,NEW.data,NEW.created_at,NEW.updated_at WHERE NEW.type='sound_event' ON CONFLICT(id) DO UPDATE SET type=excluded.type,week_group=excluded.week_group,data=excluded.data,created_at=excluded.created_at,updated_at=excluded.updated_at;
END;
CREATE TRIGGER IF NOT EXISTS gate_mirror_records_delete AFTER DELETE ON records BEGIN
 DELETE FROM gate_v2_buses WHERE id=OLD.id AND OLD.type='bus';
 DELETE FROM gate_v2_dorms WHERE id=OLD.id AND OLD.type='dorm';
 DELETE FROM gate_v2_archives WHERE id=OLD.id AND OLD.type='archive';
 DELETE FROM gate_v2_config WHERE id=OLD.id AND OLD.type='config';
 DELETE FROM gate_v2_sound_events WHERE id=OLD.id AND OLD.type='sound_event';
END;
