import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {onRequestGet,onRequestPost} from '../../../functions/api/persistence.js';
import {normalizeDraft,validateInitialization} from '../../../functions/api/persistence-core.mjs';
const migration = name => readFileSync(new URL(`../../../migrations/${name}`,import.meta.url),'utf8');
const stamp='2026-09-21T01:00:00.000Z';
const draft={action:'save_draft',proposed_week_group:'WG26051',rows:[
  {sdq:'321 TRS',sec:'01',inter_sec:'02',dorm_name:'A01',sex:'female',band:true,space_force:false,load:42},
  {sdq:'322 TRS',sec:'03',dorm_name:'B02',sex:'male',band:false,space_force:true,load:48}
],receiving_windows:{receiving_day_one_start:'2026-09-22T17:00',receiving_day_one_end:'2026-09-22T21:00'},import_review:{published_total:90,band_decision:'some'}};
function fixture(){
  const native=new DatabaseSync(':memory:');
  native.exec('PRAGMA foreign_keys=ON;CREATE TABLE records(id TEXT PRIMARY KEY,type TEXT NOT NULL,week_group TEXT,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);');
  native.exec(migration('0003_gate_persistence_foundation.sql'));
  native.exec(migration('0004_gate_record_audit_triggers.sql'));
  let failWrite=false;
  const DB={prepare(sql){let args=[];return {
    bind(...values){args=values;return this;},
    async first(){return native.prepare(sql).get(...args)??null;},
    async all(){return {results:native.prepare(sql).all(...args)};},
    async run(){if(failWrite){failWrite=false;throw new Error('Injected write failure');}const result=native.prepare(sql).run(...args);return {meta:{changes:Number(result.changes)}};},
    async execute(){return /^\s*(SELECT|WITH|PRAGMA)\b/i.test(sql)?this.all():this.run();}
  };},async batch(statements){native.exec('BEGIN');try{const results=[];for(const item of statements)results.push(await item.execute());native.exec('COMMIT');return results;}catch(e){native.exec('ROLLBACK');throw e;}}};
  const env={DB,GATE_PERSISTENCE_ENABLED:'true',AUTH_SECRET:'fixture-only'},data={session:{role:'instructor'}};
  async function post(body){const request=new Request('https://gate.example/api/persistence',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://gate.example'},body:JSON.stringify(body)});const response=await onRequestPost({request,env,data});return {status:response.status,body:await response.json()};}
  async function get(mode='health'){const response=await onRequestGet({request:new Request(`https://gate.example/api/persistence?mode=${mode}`),env,data});return {status:response.status,body:await response.json()};}
  return {native,env,post,get,failNextWrite(){failWrite=true;}};
}
function addRecord(db,id,type,wg,extra={}){const data=JSON.stringify({__backendId:id,type,week_group:wg,...extra});db.prepare('INSERT INTO records(id,type,week_group,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,type,wg,data,stamp,stamp);}
async function startCycle(f){const saved=await f.post(draft);assert.equal(saved.status,201);const started=await f.post({action:'initialize',draft_id:saved.body.draft.draft_id,revision:1});assert.equal(started.status,200,JSON.stringify(started.body));return {saved,started};}
test('exact ten tables and twelve triggers; health requires parity and both migrations',async()=>{const f=fixture();assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table' AND name LIKE 'gate_%'").get().n,10);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='trigger'").get().n,12);assert.equal((await f.get()).body.ready,true);});
test('legacy writes mirror without deleting source data',()=>{const f=fixture();addRecord(f.native,'bus1','bus','WG26050',{status:'active'});addRecord(f.native,'dorm1','dorm','WG26050',{state:'empty'});addRecord(f.native,'cfg','config','',{key:'week_group',value:'WG26050'});assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM records').get().n,3);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM gate_v2_buses').get().n,1);const payload=JSON.stringify({type:'bus',week_group:'WG26050',status:'arrived'});f.native.prepare('UPDATE records SET data=? WHERE id=?').run(payload,'bus1');assert.equal(f.native.prepare('SELECT data FROM gate_v2_buses WHERE id=?').get('bus1').data,payload);f.native.prepare('DELETE FROM records WHERE id=?').run('bus1');assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM gate_v2_buses').get().n,0);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM records').get().n,2);});
test('one active cycle and append-only audit/amendment protections',()=>{const f=fixture();f.native.prepare("INSERT INTO gate_week_groups(cycle_id,week_group,state) VALUES('one','WG26050','active')").run();assert.throws(()=>f.native.prepare("INSERT INTO gate_week_groups(cycle_id,week_group,state) VALUES('two','WG26051','active')").run(),/UNIQUE/);f.native.prepare("INSERT INTO gate_audit_events(event_id,entity_type,entity_id,event_type,actor_role) VALUES('audit','bus','id','created','instructor')").run();assert.throws(()=>f.native.prepare("DELETE FROM gate_audit_events WHERE event_id='audit'").run(),/append-only/);f.native.prepare("INSERT INTO gate_archive_amendments(amendment_id,archive_id,amendment_number,amendment_type,reason,changes_json,actor_role) VALUES('amend','archive',1,'correction','Valid reason','{}','instructor')").run();assert.throws(()=>f.native.prepare("UPDATE gate_archive_amendments SET reason='wrong' WHERE amendment_id='amend'").run(),/append-only/);});
test('draft revision conflict does not overwrite current save',async()=>{const f=fixture(),saved=await f.post(draft);assert.equal(saved.status,201);const id=saved.body.draft.draft_id;const changed=await f.post({...draft,draft_id:id,revision:1,rows:[{...draft.rows[0],load:43}]});assert.equal(changed.status,200);assert.equal(changed.body.draft.revision,2);assert.equal((await f.post({...draft,draft_id:id,revision:1})).status,409);assert.equal((await f.get('draft')).body.draft.rows[0].load,43);});
test('invalid input fails rather than truncate, discard, or coerce',()=>{assert.throws(()=>normalizeDraft({...draft,proposed_week_group:'WG'+'1'.repeat(30)}),/exceeds/);assert.throws(()=>normalizeDraft({...draft,rows:[{...draft.rows[0],sdq:'x'.repeat(49)}]}),/exceeds/);assert.throws(()=>normalizeDraft({...draft,rows:[{...draft.rows[0],extra:'retain'}]}),/silently discarded/);assert.throws(()=>normalizeDraft({...draft,rows:[{...draft.rows[0],sex:'invalid'}]}),/Invalid sex/);assert.throws(()=>normalizeDraft({...draft,rows:[{...draft.rows[0],band:true,space_force:true}]}),/Band and Space Force/);assert.throws(()=>normalizeDraft({...draft,receiving_windows:{receiving_day_one_start:'2026-09-22T21:00',receiving_day_one_end:'2026-09-22T17:00'}}),/Receiving window/);assert.throws(()=>validateInitialization(normalizeDraft({...draft,rows:[draft.rows[0],draft.rows[0]]})),/Duplicate/);});
test('initialization creates only one active cycle and consumes one draft',async()=>{const f=fixture(),{saved,started}=await startCycle(f);const repeat=await f.post({action:'initialize',draft_id:saved.body.draft.draft_id,revision:1});assert.equal(repeat.status,200);assert.equal(repeat.body.idempotent,true);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='dorm'").get().n,2);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM gate_v2_dorms').get().n,2);assert.equal(f.native.prepare('SELECT status FROM gate_input_drafts').get().status,'consumed');assert.equal((await f.post(draft)).status,409);assert.equal((await f.get()).body.ready,true);assert.ok(started.body.cycle_id);});
test('closeout preserves byte-exact source records including sound events and custom fields; replay is idempotent even after next cycle starts',async()=>{const f=fixture(),{started}=await startCycle(f);const dorm=f.native.prepare("SELECT id,data FROM records WHERE type='dorm' ORDER BY id LIMIT 1").get();f.native.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...JSON.parse(dorm.data),custom_dorm_field:'preserve',notes:'original notes'}),dorm.id);addRecord(f.native,'bus1','bus','WG26051',{status:'arrived',otw_count:23,custom_bus_field:'keep'});addRecord(f.native,'sound1','sound_event','WG26051',{event:'alert',custom_sound_field:'keep'});const original=f.native.prepare("SELECT id,type,week_group,data,created_at,updated_at FROM records WHERE week_group='WG26051' AND type IN ('dorm','bus','sound_event') ORDER BY created_at,id").all();const close=await f.post({action:'closeout',cycle_id:started.body.cycle_id});assert.equal(close.status,200,JSON.stringify(close.body));const archive=JSON.parse(f.native.prepare("SELECT data FROM records WHERE type='archive'").get().data);assert.deepEqual(JSON.parse(archive.source_records_json),JSON.parse(JSON.stringify(original)));assert.equal(archive.source_record_count,original.length);assert.equal(archive.source_snapshot_format,'lossless-record-rows-v1');assert.equal(JSON.parse(archive.dorm_data).length,2);assert.equal(archive.total_expected,90);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type IN ('dorm','bus','sound_event')").get().n,0);assert.equal(f.native.prepare("SELECT state FROM gate_week_groups WHERE cycle_id=?").get(started.body.cycle_id).state,'closed');const retry=await f.post({action:'closeout',cycle_id:started.body.cycle_id});assert.equal(retry.status,200);assert.equal(retry.body.idempotent,true);assert.equal(retry.body.archive_id,close.body.archive_id);const next=await f.post({...draft,proposed_week_group:'WG26052'});assert.equal(next.status,201);const newCycle=await f.post({action:'initialize',draft_id:next.body.draft.draft_id,revision:1});assert.equal(newCycle.status,200);assert.equal((await f.post({action:'closeout',cycle_id:started.body.cycle_id})).body.archive_id,close.body.archive_id);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='dorm'").get().n,2);assert.equal((await f.post({action:'closeout',cycle_id:'wrong-cycle'})).status,409);});
test('injected archive insert failure rolls back without deleting or consuming current state',async()=>{const f=fixture(),{started}=await startCycle(f),before=f.native.prepare("SELECT id,data FROM records WHERE type='dorm' ORDER BY id").all();f.failNextWrite();assert.equal((await f.post({action:'closeout',cycle_id:started.body.cycle_id})).status,409);assert.deepEqual(f.native.prepare("SELECT id,data FROM records WHERE type='dorm' ORDER BY id").all(),before);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='archive'").get().n,0);assert.equal(f.native.prepare('SELECT state FROM gate_week_groups').get().state,'active');});
test('oversized archive fails closed without truncation or deleting sources',async()=>{const f=fixture(),{started}=await startCycle(f);addRecord(f.native,'large-bus','bus','WG26051',{status:'active',custom_payload:'x'.repeat(1850000)});const failed=await f.post({action:'closeout',cycle_id:started.body.cycle_id});assert.equal(failed.status,409);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='bus'").get().n,1);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='archive'").get().n,0);assert.equal(f.native.prepare('SELECT state FROM gate_week_groups').get().state,'active');});
test('injected initialization failure retains original state and unconsumed draft',async()=>{const f=fixture(),saved=await f.post(draft);f.failNextWrite();assert.equal((await f.post({action:'initialize',draft_id:saved.body.draft.draft_id,revision:1})).status,409);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM records').get().n,0);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM gate_week_groups').get().n,0);assert.equal(f.native.prepare('SELECT status FROM gate_input_drafts').get().status,'draft');});
test('legacy active-cycle adoption does not duplicate live records or cycles',async()=>{const f=fixture();addRecord(f.native,'dorm','dorm','WG26050',{dorm_name:'A01',max_load:48});addRecord(f.native,'config','config','',{key:'week_group',value:'WG26050'});assert.equal((await f.get()).body.adoption_required,true);const adopted=await f.post({action:'adopt'});assert.equal(adopted.status,200,JSON.stringify(adopted.body));assert.equal((await f.post({action:'adopt'})).body.adopted,false);assert.equal(f.native.prepare('SELECT COUNT(*) AS n FROM gate_week_groups').get().n,1);assert.equal(f.native.prepare("SELECT COUNT(*) AS n FROM records WHERE type='dorm'").get().n,1);});
